dist: xenial
language: java
jdk:
  - openjdk8

git:
  depth: 1 # an optimization since we won't be committing anything
  quiet: true

services:
- docker # In order to run DBMS such as DB2, MSSQL and Oracle

stages:
- test

cache:
  directories:
    - $HOME/.m2/repository
    - ${TRAVIS_BUILD_DIR}/container

jobs:
  include:
  - stage: test

    # ----------------------- db2 -----------------------
    env: DB=db2_travis-ci
    before_install:
      - docker run -d -p 50000:50000 --name db2 -e DB2INST1_PASSWORD=dzqAbmZwnN8c -e LICENSE=accept -e DBNAME=db2 -e ARCHIVE_LOGS=false --privileged=true -v ${TRAVIS_BUILD_DIR}/container:/database ibmcom/db2
      - docker ps
      - source .travisci/setup.sh
    #before_script:
    # - echo 'Waiting for DB2 to be ready...' && while ! docker logs db2 2>&1 | grep 'Setup has completed' ; do echo 'Waiting for DB2 to be ready...'; sleep 5; done;
    script:
      - echo "Starting DB2 build"
      - sh .travisci/run_tests.sh
    before_cache:
      - docker stop db2
